### ISSUE TITLE
Use of 3rd party library

### ISSUE THREAD

**Issue by HeidiHansen** [the-dagger/MLKitAndroid#6]
Hi,

It would be helpful if you could indicate that this project includes the use of a third party library from WonderKiln.  It would be preferable to see an MLKit android project that doesn't use third-party libraries, or warns if this is the case.  Thank you!

**Comment by the-dagger** [comment]
Sounds good, I will do that.
P.S. The library is used only to capture an image, it has nothing to do with actual functionality that's provided by the MLKit APIs.

**Comment by HeidiHansen** [comment]
Thanks for the clarification.  I understand this isn't the best place to ask, but do you possibly know how to capture the QR data without capturing an image first? The pre-MLKit Google barcode scanner project captures and displays the QR data while the camera preview is active and it is highly accurate.  I've integrated the deprecated lib and gotten it to work, but it's so hideous and massive and I'm working on a more elegant solution that, preferably, uses MLKit instead.  Evidently, all of this deprecated java code from the barcode reader is simply integrated into the MLKit functionality, so the ability to do this is already baked in... it's just not well documented by Google.  I'm referring to [this barcode reader](https://github.com/googlesamples/android-vision) project

**Comment by the-dagger** [comment]
Sure, I think that should be possible.
As a matter of fact, I was planning to update the samples with frame processing so that clicking a picture wasn't required.


Can you take a look at this blogpost and let me know if integrating MLKit with the frameProcessing outlined here works for you?

Counting Items in Real-Time with Fritz Object Detection for Android by Harshit Dwivedi https://link.medium.com/J6L8X0yYMR

If it doesn't, I'll update the samples in a day or two :)
